variables:
  ISABELLE_HOME_USER_DIR: "/home/isabelle/.isabelle"
  TIMEOUT_SCALE: "1.8"

image: jecb96/isabelle:2018

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - cache/

stages:
  - dependency
  - mustWork
  - canFail


before_script:
  - if [ ! -z "$(ls -A cache)" ]; then mv cache/* $ISABELLE_HOME_USER_DIR; fi
  - find $ISABELLE_HOME_USER_DIR

after_script:
  - find $ISABELLE_HOME_USER_DIR
  - rm -rf cache/*
  - mv $ISABELLE_HOME_USER_DIR/* cache/



#####################################
## Test Jobs
#####################################

## Look in the "ROOT" file to see the sessions and add files


dependency:
  stage: dependency
  script:
    - isabelle build -S -D . -j$NUMBER_SIMULT_SESSIONS -o timeout_scale=$TIMEOUT_SCALE -n -v || if [ $? -eq 1 ]; then exit 0; else exit $?; fi
  tags:
    - docker
    - private


mustWork:
  stage: mustWork
  script:
    - isabelle build -S -d . -j$NUMBER_SIMULT_SESSIONS -o timeout_scale=$TIMEOUT_SCALE -v -b -g mustWork
  tags:
    - docker
    - private


canFail:
  stage: canFail
  allow_failure: true   # for now, sorrys are allowed
  script:
    - isabelle build -S -d . -j$NUMBER_SIMULT_SESSIONS -o timeout_scale=$TIMEOUT_SCALE -v -b -g canFail
  tags:
    - docker
    - private