# load docker image with isabelle-support
image: jecb96/isabelle:2018




#####################################
## Setup Stuff
#####################################

## run this bevore every stage

before_script:
  - if [ ! -z "$(ls -A cache)" ]; then mv cache/* /home/isabelle/.isabelle; fi
  - find /home/isabelle/.isabelle

  # run after every stage
after_script:
  - find /home/isabelle/.isabelle
  - mv /home/isabelle/.isabelle/* cache/


cache:
  key: "$CI_COMMIT_REF_NAME"  # cache per branch
  paths:
    - cache/
#    - /home/isabelle/.isabelle



# stages are run one after another, it the previous stage is successful
stages:
  - dependency
  - mustWork
  - canFail





#####################################
## Main Tests
#####################################

## Look in the "ROOT" file to see the sessions and add files


  # check for ALL sessions in ROOT if the dependencies are working
  # -D .  loads all sessions in directory
  # -n    checks imports
dependency:
  stage: dependency
  script:
    - isabelle version
    - isabelle build -D . -j2 -n -v || if [ $? -eq 1 ]; then exit 0; else exit $?; fi



  # run everything in the group "mustWork" (as defined in ROOT)
  # -d .      make sessions addable (but do not load them)
  # -g sorry  load all "sorry" sessions
  # -b        save heap files
mustWork:
  stage: mustWork
  script:
    - isabelle version
    - isabelle build -d . -j2 -v -b -g mustWork



  # run everything in the group "canFail" (as defined in ROOT)
  # -d .          make sessions addable (but do not load them)
  # -g verified   load all "verified" sessions
  # -b            save heap files
canFail:
  stage: canFail
  allow_failure: true   #for now, sorrys are allowed
  script:
    - isabelle version
    - isabelle build -d . -j2 -v -b -g canFail
