image: jecb96/isabelle:2018

cache:
  key: "$CI_COMMIT_REF_SLUG"  # cache per branch
  paths:
    - /home/isabelle/.isabelle/


stages:
  - dependency
  - mustWork
  - canFail



#####################################
## Test Jobs
#####################################

## Look in the "ROOT" file to see the sessions and add files


  # check for ALL sessions in ROOT if the dependencies are working
  # -D .  loads all sessions in directory
  # -n    checks imports
dependency:
  stage: dependency
  script:
    - isabelle build -D . -j2 -o timeout_scale=1.8 -n -v || if [ $? -eq 1 ]; then exit 0; else exit $?; fi



  # run everything in the group "mustWork" (as defined in ROOT)
  # -d .      make sessions addable (but do not load them)
  # -g sorry  load all "sorry" sessions
  # -b        save heap files
mustWork:
  stage: mustWork
  script:
    - find /home/isabelle/.isabelle
    - isabelle build -d . -j2 -o timeout_scale=1.8 -v -b -g mustWork



  # run everything in the group "canFail" (as defined in ROOT)
  # -d .          make sessions addable (but do not load them)
  # -g verified   load all "verified" sessions
  # -b            save heap files
canFail:
  stage: canFail
  allow_failure: true   #for now, sorrys are allowed
  script:
    - isabelle build -d . -j2 -o timeout_scale=1.8 -v -b -g canFail
